/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface INexeraVerifierEntrypointInterface extends ethers.utils.Interface {
  functions: {
    "addScenarioVerifier(address)": FunctionFragment;
    "deleteScenarioVerifier(address)": FunctionFragment;
    "disableScenario(address)": FunctionFragment;
    "enableScenario(address)": FunctionFragment;
    "isAllowedForEntrypoint(address)": FunctionFragment;
    "updateScenarioVerifier(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addScenarioVerifier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteScenarioVerifier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "disableScenario",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "enableScenario",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowedForEntrypoint",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateScenarioVerifier",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addScenarioVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteScenarioVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableScenario",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableScenario",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedForEntrypoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateScenarioVerifier",
    data: BytesLike
  ): Result;

  events: {};
}

export class INexeraVerifierEntrypoint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: INexeraVerifierEntrypointInterface;

  functions: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addScenarioVerifier(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteScenarioVerifier(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disableScenario(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enableScenario(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isAllowedForEntrypoint(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateScenarioVerifier(
    oldScenarioVerifierAddress: string,
    newScenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
