/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface NexeraVerifierEntrypointInterface extends ethers.utils.Interface {
  functions: {
    "addScenarioVerifier(address)": FunctionFragment;
    "deleteScenarioVerifier(address)": FunctionFragment;
    "disableScenario(address)": FunctionFragment;
    "enableScenario(address)": FunctionFragment;
    "getIsScenarioEnabled(address)": FunctionFragment;
    "getScenarioVerifierAddress(uint256)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "isAllowedForEntrypoint(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateScenarioVerifier(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addScenarioVerifier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteScenarioVerifier",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "disableScenario",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "enableScenario",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getIsScenarioEnabled",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getScenarioVerifierAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isAllowedForEntrypoint",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateScenarioVerifier",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addScenarioVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteScenarioVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableScenario",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableScenario",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIsScenarioEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScenarioVerifierAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedForEntrypoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateScenarioVerifier",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint64)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ScenarioVerifierAdded(address)": EventFragment;
    "ScenarioVerifierDeleted(address)": EventFragment;
    "ScenarioVerifierDisabled(address)": EventFragment;
    "ScenarioVerifierEnabled(address)": EventFragment;
    "ScenarioVerifierUpdated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScenarioVerifierAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScenarioVerifierDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScenarioVerifierDisabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScenarioVerifierEnabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ScenarioVerifierUpdated"): EventFragment;
}

export type InitializedEvent = TypedEvent<[BigNumber] & { version: BigNumber }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ScenarioVerifierAddedEvent = TypedEvent<
  [string] & { scenarioVerifierAddress: string }
>;

export type ScenarioVerifierDeletedEvent = TypedEvent<
  [string] & { scenarioVerifierAddress: string }
>;

export type ScenarioVerifierDisabledEvent = TypedEvent<
  [string] & { scenarioVerifierAddress: string }
>;

export type ScenarioVerifierEnabledEvent = TypedEvent<
  [string] & { scenarioVerifierAddress: string }
>;

export type ScenarioVerifierUpdatedEvent = TypedEvent<
  [string, string] & {
    oldScenarioVerifierAddress: string;
    newScenarioVerifierAddress: string;
  }
>;

export class NexeraVerifierEntrypoint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: NexeraVerifierEntrypointInterface;

  functions: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getIsScenarioEnabled(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getScenarioVerifierAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addScenarioVerifier(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteScenarioVerifier(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disableScenario(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  enableScenario(
    scenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getIsScenarioEnabled(
    scenarioVerifierAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getScenarioVerifierAddress(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isAllowedForEntrypoint(
    user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateScenarioVerifier(
    oldScenarioVerifierAddress: string,
    newScenarioVerifierAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getIsScenarioEnabled(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getScenarioVerifierAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(newOwner: string, overrides?: CallOverrides): Promise<void>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint64)"(
      version?: null
    ): TypedEventFilter<[BigNumber], { version: BigNumber }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[BigNumber], { version: BigNumber }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ScenarioVerifierAdded(address)"(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    ScenarioVerifierAdded(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    "ScenarioVerifierDeleted(address)"(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    ScenarioVerifierDeleted(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    "ScenarioVerifierDisabled(address)"(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    ScenarioVerifierDisabled(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    "ScenarioVerifierEnabled(address)"(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    ScenarioVerifierEnabled(
      scenarioVerifierAddress?: null
    ): TypedEventFilter<[string], { scenarioVerifierAddress: string }>;

    "ScenarioVerifierUpdated(address,address)"(
      oldScenarioVerifierAddress?: null,
      newScenarioVerifierAddress?: null
    ): TypedEventFilter<
      [string, string],
      { oldScenarioVerifierAddress: string; newScenarioVerifierAddress: string }
    >;

    ScenarioVerifierUpdated(
      oldScenarioVerifierAddress?: null,
      newScenarioVerifierAddress?: null
    ): TypedEventFilter<
      [string, string],
      { oldScenarioVerifierAddress: string; newScenarioVerifierAddress: string }
    >;
  };

  estimateGas: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getIsScenarioEnabled(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getScenarioVerifierAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteScenarioVerifier(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    enableScenario(
      scenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getIsScenarioEnabled(
      scenarioVerifierAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getScenarioVerifierAddress(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isAllowedForEntrypoint(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateScenarioVerifier(
      oldScenarioVerifierAddress: string,
      newScenarioVerifierAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
