/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PoseidonUnit6L,
  PoseidonUnit6LInterface,
} from "../PoseidonUnit6L";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[6]",
        name: "",
        type: "uint256[6]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60808060405234601857607b908161001e823930815050f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63f5b4a78814602857600080fd5b60c03660031901126041573660c4116041576020918152f35b5080fdfea26469706673582212204cc6b8f5717b6b25ec251cb6b9e74403dc15ea332497e4c81170b6c567966f2564736f6c63430008100033";

export class PoseidonUnit6L__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PoseidonUnit6L> {
    return super.deploy(overrides || {}) as Promise<PoseidonUnit6L>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoseidonUnit6L {
    return super.attach(address) as PoseidonUnit6L;
  }
  connect(signer: Signer): PoseidonUnit6L__factory {
    return super.connect(signer) as PoseidonUnit6L__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonUnit6LInterface {
    return new utils.Interface(_abi) as PoseidonUnit6LInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonUnit6L {
    return new Contract(address, _abi, signerOrProvider) as PoseidonUnit6L;
  }
}
