/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PoseidonUnit5L,
  PoseidonUnit5LInterface,
} from "../PoseidonUnit5L";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[5]",
        name: "",
        type: "uint256[5]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60808060405234601857607b908161001e823930815050f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c634937a25814602857600080fd5b60a03660031901126041573660a4116041576020918152f35b5080fdfea264697066735822122092015cc34bb2d94c7f9d009687d1b243273cca33047bae03f1b4dca739b86b9a64736f6c63430008100033";

export class PoseidonUnit5L__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PoseidonUnit5L> {
    return super.deploy(overrides || {}) as Promise<PoseidonUnit5L>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoseidonUnit5L {
    return super.attach(address) as PoseidonUnit5L;
  }
  connect(signer: Signer): PoseidonUnit5L__factory {
    return super.connect(signer) as PoseidonUnit5L__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonUnit5LInterface {
    return new utils.Interface(_abi) as PoseidonUnit5LInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonUnit5L {
    return new Contract(address, _abi, signerOrProvider) as PoseidonUnit5L;
  }
}
