/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PoseidonUnit4L,
  PoseidonUnit4LInterface,
} from "../PoseidonUnit4L";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[4]",
        name: "",
        type: "uint256[4]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60808060405234601857607b908161001e823930815050f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63248f667714602857600080fd5b6080366003190112604157366084116041576020918152f35b5080fdfea2646970667358221220de5da88dce3ae66ceb3a42876068a8ce374ed35ae673596a179f0cc9709b7bae64736f6c63430008100033";

export class PoseidonUnit4L__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PoseidonUnit4L> {
    return super.deploy(overrides || {}) as Promise<PoseidonUnit4L>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoseidonUnit4L {
    return super.attach(address) as PoseidonUnit4L;
  }
  connect(signer: Signer): PoseidonUnit4L__factory {
    return super.connect(signer) as PoseidonUnit4L__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonUnit4LInterface {
    return new utils.Interface(_abi) as PoseidonUnit4LInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonUnit4L {
    return new Contract(address, _abi, signerOrProvider) as PoseidonUnit4L;
  }
}
