/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PoseidonUnit3L,
  PoseidonUnit3LInterface,
} from "../PoseidonUnit3L";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[3]",
        name: "",
        type: "uint256[3]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60808060405234601857607b908161001e823930815050f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c6325cc70e814602857600080fd5b6060366003190112604157366064116041576020918152f35b5080fdfea264697066735822122050039979b1ade3d3403c77aeeb05836bc8cd1a54e724ab0e329656b95354ffb764736f6c63430008100033";

export class PoseidonUnit3L__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PoseidonUnit3L> {
    return super.deploy(overrides || {}) as Promise<PoseidonUnit3L>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoseidonUnit3L {
    return super.attach(address) as PoseidonUnit3L;
  }
  connect(signer: Signer): PoseidonUnit3L__factory {
    return super.connect(signer) as PoseidonUnit3L__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PoseidonUnit3LInterface {
    return new utils.Interface(_abi) as PoseidonUnit3LInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonUnit3L {
    return new Contract(address, _abi, signerOrProvider) as PoseidonUnit3L;
  }
}
