#!/bin/sh

# run a local tezos sandbox
# https://tezos.gitlab.io/flextesa/

project=$1
name="$project"-sandbox

image=oxheadalpha/flextesa:latest
script=oxfordbox

docker run --rm --name "$name" --detach -p 20000:20000 \
       -e block_time=1 \
       -e flextesa_node_cors_origin='*' \
       "$image" "$script" start

# let it time to bootstrap..
sleep 15

# add missing accounts
docker exec "$name" octez-client import secret key frank \
    unencrypted:edskS7YYeT85SiRZEHPFjDpCAzCuUaMwYFi39cWPfguovTuNqxU3U9hXo7LocuJmr7hxkesUFkmDJh26ubQGehwXY8YiGXYCvU

docker exec "$name" octez-client import secret key user \
    unencrypted:edskRn9jTrK2LLXeBQWczJHEDgjYPscHugVZ3TryQJBkH5DGF6MYEx8ysihSonyNrCSweGZdpsYi6EB4Fvnbyw3kfhZHGiFccQ

# fund them
reveal_fee=0.06425

docker exec "$name" octez-client transfer 10000 from alice to frank --burn-cap "$reveal_fee"
docker exec "$name" octez-client transfer 10000 from alice to user --burn-cap "$reveal_fee"