#!/bin/sh

# run a local tezos sandbox
# https://github.com/tez-capital/tezbox

project=$1
name="$project"-sandbox

image=ghcr.io/tez-capital/tezbox:tezos-v20.2
script=parisbox

docker run --rm --name "$name"  \
    -v $(pwd)/tezbox-overrides/sandbox-parameters.hjson:/tezbox/overrides/protocols/PsParisC/sandbox-parameters.hjson \
    -v $(pwd)/tezbox-overrides/accounts.hjson:/tezbox/overrides/accounts.hjson \
    -d -p 8732:8732 $image $script


# let it time to bootstrap..
sleep 10
