/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INexeraVerifierEntrypoint,
  INexeraVerifierEntrypointInterface,
} from "../INexeraVerifierEntrypoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "scenarioVerifierAddress",
        type: "address",
      },
    ],
    name: "addScenarioVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isAllowedForEntrypoint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INexeraVerifierEntrypoint__factory {
  static readonly abi = _abi;
  static createInterface(): INexeraVerifierEntrypointInterface {
    return new utils.Interface(_abi) as INexeraVerifierEntrypointInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INexeraVerifierEntrypoint {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as INexeraVerifierEntrypoint;
  }
}
